AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Lambda Stats Service
  
  SAM Template for deploying a Lambda Statistics Service

Globals:
  Function:
    Timeout: 5

Parameters:
  Environment:
    Description: Environment to which the application is deployed
    Type: String
    Default: dev

Resources:
  LambdaStatsFunction:
    Type: AWS::Serverless::Function 
    Properties:
      CodeUri: lambda-stats/
      Handler: lambda-stats
      Runtime: go1.x
      FunctionName: !Sub '${Environment}-lambda-stats-function'
      Architectures:
        - x86_64
      Events:
        CatchAll:
          Type: Api 
          Properties:
            RestApiId:
              Ref: AccessLoggedApi
            Path: /lambdas
            Method: GET
      Environment: 
        Variables:
          ENVIRONMENT: !Ref Environment

  LambdaLogGroup:
        Type: AWS::Logs::LogGroup
        DependsOn: [ LambdaStatsFunction ]
        Properties:
              RetentionInDays: 3
              LogGroupName: !Join ['', ['/aws/lambda/', !Ref LambdaStatsFunction]]

  AccessLoggedApi:
    Type: AWS::Serverless::Api
    Properties:
      StageName: !Ref Environment
      OpenApiVersion: "3.0.3"
      AccessLogSetting:
        DestinationArn: !GetAtt AccessLogGroup.Arn
        Format: '{"requestTime":"$context.requestTime","requestId":"$context.requestId","httpMethod":"$context.httpMethod","path":"$context.path","resourcePath":"$context.resourcePath","status":$context.status,"responseLatency":$context.responseLatency,"xrayTraceId":"$context.xrayTraceId","integrationRequestId":"$context.integration.requestId","functionResponseStatus":"$context.integration.status","integrationLatency":"$context.integration.latency","integrationServiceStatus":"$context.integration.integrationStatus","ip":"$context.identity.sourceIp","userAgent":"$context.identity.userAgent"}'

  AccessLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
          RetentionInDays: 3
          LogGroupName: !Join ['', ['/aws/apigateway/', !Ref AWS::StackName]]

Outputs:
  LambdaStatsFunction:
    Description: "Lambda Function ARN"
    Value: !GetAtt LambdaStatsFunction.Arn