package config

var (
	SupportedRegions = []string{
		"us-east-2",
		"us-east-1",
		"us-west-1",
		"us-west-2",
		// "af-south-1",
		// "ap-east-1",
		// "ap-southeast-3",
		"ap-south-1",
		"ap-northeast-3",
		"ap-northeast-2",
		"ap-southeast-1",
		"ap-southeast-2",
		"ap-northeast-1",
		"ca-central-1",
		"eu-central-1",
		"eu-west-1",
		"eu-west-2",
		// "eu-south-1",
		"eu-west-3",
		"eu-north-1",
		// "eu-central-2",
		// "me-south-1",
		// "me-central-1",
		"sa-east-1",
		// "us-gov-east-1",
		// "us-gov-west-1",
	}

	SupportedRuntimes = []string{
		"nodejs18.x",
		"nodejs16.x",
		"nodejs14.x",
		"python3.10",
		"python3.9",
		"python3.8",
		"python3.7",
		"java17",
		"java11",
		"java8.al2",
		"java8",
		"dotnet7",
		"dotnet6",
		"go1.x",
		"ruby3.2",
		"ruby2.7",
		"provided.al2",
		"provided",
	}
)
