name: SAM
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
      - uses: aws-actions/setup-sam@v2
      - uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}
      # sam build 
      - run: sam build --use-container

      # sam deploy
      - run: sam deploy --no-confirm-changeset --no-fail-on-empty-changeset --stack-name lambda-stats --s3-bucket ${{ secrets.AWS_SAM_BUCKET }} --capabilities CAPABILITY_IAM --region ${{ secrets.AWS_REGION }}

      # verify deploy
      - run: |
         export API_ID=$(aws apigateway get-rest-apis --region ${{ secrets.AWS_REGION }} --query "items[?name == 'dev-lambda-stats-api']" | jq '.[].id' | tr -d "\"")
         export API_KEY=$( aws apigateway get-api-keys --region ${{ secrets.AWS_REGION }} --query "items[?stageKeys && contains(stageKeys, '$API_ID/dev')]" --include-value | jq '.[].value' | tr -d "\"")
         curl --silent --fail --show-error -H "x-api-key: $API_KEY" -o /dev/null "https://$API_ID.execute-api.${{ secrets.AWS_REGION }}.amazonaws.com/dev/lambdas" 